#
# Copyright (C) 2018 rosysong@rosinson.com
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

PKG_NAME:=xderm-mini
PKG_VERSION:=2.9
PKG_RELEASE:=1
PKG_LICENSE:=GPL-2.0

PKG_MAINTAINER:=Rosy Song <rosysong@rosinson.com>

PKG_BUILD_DIR := $(BUILD_DIR)/$(PKG_NAME)

include $(INCLUDE_DIR)/package.mk

define Package/xderm-mini
  SECTION:=net
  CATEGORY:=Network
  DEPENDS:=
  TITLE:=Tools Inject xderm-mini
endef

define Package/xderm-mini/description
 xderm-mini ssh v2ray trojan
endef

define Build/Prepare
endef

define Build/Configure
endef

define Build/Compile
endef

define Package/xderm-mini/install
endef

$(eval $(call BuildPackage,xderm-mini))
